INSERT INTO POSTS (USER_ID, BODY)
VALUES (1, "I accidenly pressede something");

INSERT INTO POSTS (USER_ID, BODY)
VALUES (2, "It was  suppused to be sned to someone else!");

INSERT INTO POSTS (USER_ID, BODY)
VALUES (3, "Ugga-bugga hugga-unga!");

UPDATE POSTS
SET BODY = "TO DELETE"
WHERE ID = 7;

UPDATE POSTS
SET BODY = "TO DELETE"
WHERE ID = 8;

UPDATE POSTS
SET BODY = "TO DELETE"
WHERE ID = 9;

COMMIT;

DELETE FROM POSTS
WHERE ID = 7;

DELETE FROM POSTS
WHERE ID = 8;

DELETE FROM POSTS
WHERE ID = 9;

COMMIT;